basePath: /
definitions:
  controllers.Response:
    properties:
      message:
        type: string
      pageInfo: {}
      results: {}
      success:
        type: boolean
    type: object
  controllers.Response401:
    properties:
      message:
        default: Unauthorized
        type: string
      success:
        default: false
        type: boolean
    type: object
  models.Movie:
    properties:
      castName:
        type: string
      directorName:
        type: string
      duration:
        description: ReleaseDate time.Time `json:"releaseDate" form:"release_date"`
        type: string
      genreName:
        type: string
      id:
        type: integer
      synopsis:
        type: string
      tag:
        description: |-
          Image *multipart.FileHeader `json:"image" form:"image" binding:"required"`
          Banner *multipart.FileHeader `json:"banner" form:"banner" binding:"required"`
        type: string
      title:
        type: string
    type: object
  models.MovieData:
    properties:
      banner:
        type: string
      castName:
        type: string
      createdAt:
        type: string
      directorName:
        type: string
      duration:
        description: ReleaseDate time.Time `json:"releaseDate" form:"release_date"`
        type: string
      genreName:
        type: string
      id:
        type: integer
      image:
        type: string
      releaseDate:
        type: string
      synopsis:
        type: string
      tag:
        description: |-
          Image *multipart.FileHeader `json:"image" form:"image" binding:"required"`
          Banner *multipart.FileHeader `json:"banner" form:"banner" binding:"required"`
        type: string
      title:
        type: string
      updatedAt:
        type: string
    required:
    - banner
    - image
    type: object
  models.TransactionResponse:
    properties:
      expiryDate:
        type: string
      status:
        type: string
      totalPrice:
        type: integer
      virtualId:
        type: string
    type: object
  models.User:
    properties:
      createdAt:
        type: string
      email:
        type: string
      firstName:
        type: string
      id:
        type: integer
      image:
        type: string
      lastName:
        type: string
      password:
        type: string
      phoneNumber:
        type: string
      point:
        type: string
      role:
        type: string
      updatedAt:
        type: string
    type: object
info:
  contact: {}
  description: backend TixIT
  title: TixIT
  version: "1.0"
paths:
  /auth/login:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk mengautentikasi user
      parameters:
      - description: ' '
        in: formData
        name: email
        required: true
        type: string
      - description: ' '
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
      summary: Login user
      tags:
      - Auth
  /auth/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk membuat user baru
      parameters:
      - description: ' '
        in: formData
        name: email
        required: true
        type: string
      - description: ' '
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
      summary: Register user
      tags:
      - Auth
  /movies:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk mendapatkan list semua movie
      parameters:
      - description: ' '
        in: query
        name: search
        type: string
      - description: ' '
        in: query
        name: sortBy
        type: string
      - description: ' '
        in: query
        name: sortOrder
        type: string
      - description: ' '
        in: query
        name: page
        type: string
      - description: ' '
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  items:
                    $ref: '#/definitions/models.MovieData'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      summary: get all list movies
      tags:
      - Movies
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk membuat movie baru
      parameters:
      - description: ' '
        in: formData
        name: title
        required: true
        type: string
      - description: ' '
        in: formData
        name: image
        required: true
        type: file
      - description: ' '
        in: formData
        name: banner
        required: true
        type: file
      - description: ' '
        in: formData
        name: tag
        required: true
        type: string
      - description: ' '
        in: formData
        name: releaseDate
        required: true
        type: string
      - description: ' '
        in: formData
        name: duration
        required: true
        type: string
      - description: ' '
        in: formData
        name: synopsis
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  $ref: '#/definitions/models.Movie'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      security:
      - ApiKeyAuth: []
      summary: create movie
      tags:
      - Movies
  /movies/{id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk menghapus movie
      parameters:
      - description: movie id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  $ref: '#/definitions/models.Movie'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      security:
      - ApiKeyAuth: []
      summary: delete movie by id
      tags:
      - Movies
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk mendapatkan list movie dari id
      parameters:
      - description: movie id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  $ref: '#/definitions/models.Movie'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      summary: get list movie by id
      tags:
      - Movies
  /orders:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk memesan tiket
      parameters:
      - description: ' '
        in: formData
        name: cinemaId
        type: integer
      - description: ' '
        in: formData
        name: movieId
        type: integer
      - description: ' '
        in: formData
        name: paymentId
        type: integer
      - collectionFormat: csv
        description: ' '
        in: formData
        items:
          type: string
        name: seats[]
        type: array
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  $ref: '#/definitions/models.TransactionResponse'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      security:
      - ApiKeyAuth: []
      summary: place order
      tags:
      - Orders
  /profiles:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk mendapatkan profile
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  $ref: '#/definitions/models.User'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      security:
      - ApiKeyAuth: []
      summary: get profile by id
      tags:
      - Profiles
  /users:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk mendapatkan list semua user
      parameters:
      - description: ' '
        in: query
        name: search
        type: string
      - description: ' '
        in: query
        name: sortBy
        type: string
      - description: ' '
        in: query
        name: sortOrder
        type: string
      - description: ' '
        in: query
        name: page
        type: string
      - description: ' '
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      security:
      - ApiKeyAuth: []
      summary: get all list users
      tags:
      - Users
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk membuat user baru
      parameters:
      - description: ' '
        in: formData
        name: email
        required: true
        type: string
      - description: ' '
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      security:
      - ApiKeyAuth: []
      summary: create user
      tags:
      - Users
  /users/{id}:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk menghapus user
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      security:
      - ApiKeyAuth: []
      summary: delete user by id
      tags:
      - Users
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk mendapatkan user
      parameters:
      - description: User id
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  $ref: '#/definitions/models.User'
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      security:
      - ApiKeyAuth: []
      summary: get users by id
      tags:
      - Users
    patch:
      consumes:
      - application/x-www-form-urlencoded
      description: untuk merubah data user
      parameters:
      - description: user id
        in: path
        name: id
        required: true
        type: integer
      - description: ' '
        in: formData
        name: email
        required: true
        type: string
      - description: ' '
        in: formData
        name: password
        required: true
        type: string
      - description: ' '
        in: formData
        name: firstName
        required: true
        type: string
      - description: ' '
        in: formData
        name: lastName
        required: true
        type: string
      - description: ' '
        in: formData
        name: phoneNumber
        required: true
        type: string
      - description: ' '
        in: formData
        name: image
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/controllers.Response'
            - properties:
                results:
                  items:
                    $ref: '#/definitions/models.User'
                  type: array
              type: object
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.Response401'
      security:
      - ApiKeyAuth: []
      summary: update user
      tags:
      - Users
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
